### PR TITLE
Added GenomicsReport example; renamed RegionStudied to GenomicsRegionStudied.

### PR DESCRIPTION
**Pull request by mlterryMitre-zz**

### CODE REVIEW

**Comment by mlterryMitre-zz** [comment]
@markkramerus - the build directory seems to have a lot of changes after I did `git pull origin master`.  I'll probably need you to check why.

**Review by markkramerus — CHANGES_REQUESTED** [review]
This has to be pulled back. There are updated files that shouldn't have been updated, such as menu.xml. You should only have a couple of updated files, but there are 31.

**Comment by mlterryMitre-zz** [comment]
changes were incorporated in PR#21 so that we can get our build file structure in a good and stable place.

**Review by mlterryMitre-zz — COMMENTED** [review]
changes look good.

**Pull request closed without merging**
